/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manriqueamador_examen2;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class NASA extends javax.swing.JFrame {

    /**
     * Creates new form NASA
     */
    public NASA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        ModificarAstronauta = new javax.swing.JDialog();
        tf_sexo1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jb_modificarAstronauta = new javax.swing.JButton();
        tf_pesoAstronauta1 = new javax.swing.JTextField();
        tf_experiencia1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tf_nombreAstronauta1 = new javax.swing.JTextField();
        tf_nacionalidad1 = new javax.swing.JTextField();
        tf_sueldo1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ModificarEliminar = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        ModificarPlaneta = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jb_modificarPlaneta = new javax.swing.JButton();
        tf_distanciaTierra1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        rd_anillos1 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        tf_nombrePlaneta1 = new javax.swing.JTextField();
        tf_tempMedia1 = new javax.swing.JTextField();
        tf_tipoSuperficie1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        ModificarNave = new javax.swing.JDialog();
        jLabel44 = new javax.swing.JLabel();
        tf_numeroSerieNave1 = new javax.swing.JTextField();
        tf_velocidadNave1 = new javax.swing.JTextField();
        tf_lugarDespejeNave1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jb_modificarNave = new javax.swing.JButton();
        cb_planetaDestinoNave1 = new javax.swing.JComboBox<>();
        cb_astronautaNave1 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        agregar2 = new javax.swing.JButton();
        ModificarSonda = new javax.swing.JDialog();
        cb_planetaDestinoSonda1 = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jb_modificarSonda = new javax.swing.JButton();
        tf_numeroSerieSonda1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tf_velocidadSonda1 = new javax.swing.JTextField();
        tf_pesoSonda1 = new javax.swing.JTextField();
        tf_materialSonda1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Expedicion = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_crearAstronauta = new javax.swing.JButton();
        tf_experiencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreAstronauta = new javax.swing.JTextField();
        tf_nacionalidad = new javax.swing.JTextField();
        tf_sueldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_sexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_pesoAstronauta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jb_crearNave = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_numeroSerieNave = new javax.swing.JTextField();
        tf_velocidadNave = new javax.swing.JTextField();
        tf_lugarDespejeNave = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_planetaDestinoNave = new javax.swing.JComboBox<>();
        cb_astronautaNave = new javax.swing.JComboBox<>();
        agregar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tf_numeroSerieSonda = new javax.swing.JTextField();
        tf_velocidadSonda = new javax.swing.JTextField();
        tf_materialSonda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cb_planetaDestinoSonda = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jb_crearSonda = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tf_pesoSonda = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSondas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaNaves = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAstronautas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPlanetas = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jb_cargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        CB_planeta = new javax.swing.JComboBox<>();
        CB_nave = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tf_nombrePlaneta = new javax.swing.JTextField();
        tf_tempMedia = new javax.swing.JTextField();
        tf_tipoSuperficie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jb_crearPlaneta = new javax.swing.JButton();
        tf_distanciaTierra = new javax.swing.JTextField();
        rd_anillos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel32.setText("Experiencia");

        jLabel33.setText("Sexo");

        jb_modificarAstronauta.setText("Modificar");
        jb_modificarAstronauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarAstronautaActionPerformed(evt);
            }
        });

        jLabel34.setText("Peso");

        jLabel35.setText("MODIFICAR ASTRONAUTAS");

        jLabel36.setText("Nombre");

        tf_nombreAstronauta1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_nombreAstronauta1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_sueldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sueldo1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Nacionalidad");

        jLabel38.setText("Sueldo");

        javax.swing.GroupLayout ModificarAstronautaLayout = new javax.swing.GroupLayout(ModificarAstronauta.getContentPane());
        ModificarAstronauta.getContentPane().setLayout(ModificarAstronautaLayout);
        ModificarAstronautaLayout.setHorizontalGroup(
            ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarAstronautaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarAstronautaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificarAstronautaLayout.createSequentialGroup()
                        .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_sexo1)
                            .addComponent(tf_nombreAstronauta1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nacionalidad1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_sueldo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_experiencia1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_pesoAstronauta1)
                            .addGroup(ModificarAstronautaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jb_modificarAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))))
                .addGap(49, 49, 49))
        );
        ModificarAstronautaLayout.setVerticalGroup(
            ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarAstronautaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel35)
                .addGap(20, 20, 20)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreAstronauta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sueldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_experiencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pesoAstronauta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(34, 34, 34)
                .addComponent(jb_modificarAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        ModificarEliminar.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        ModificarEliminar.add(Eliminar);

        jLabel39.setText("Tipo de superficie");

        jLabel40.setText("Distancia con la tierra");

        jb_modificarPlaneta.setText("Modificar");
        jb_modificarPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarPlanetaActionPerformed(evt);
            }
        });

        jLabel41.setText("MODIFICAR PLANETAS");

        rd_anillos1.setText("Posee anillos");

        jLabel42.setText("Nombre");

        tf_nombrePlaneta1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_nombrePlaneta1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_tipoSuperficie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tipoSuperficie1ActionPerformed(evt);
            }
        });

        jLabel43.setText("Temp. media");

        javax.swing.GroupLayout ModificarPlanetaLayout = new javax.swing.GroupLayout(ModificarPlaneta.getContentPane());
        ModificarPlaneta.getContentPane().setLayout(ModificarPlanetaLayout);
        ModificarPlanetaLayout.setHorizontalGroup(
            ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarPlanetaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificarPlanetaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ModificarPlanetaLayout.createSequentialGroup()
                        .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombrePlaneta1)
                            .addComponent(tf_tempMedia1)
                            .addComponent(tf_tipoSuperficie1)
                            .addComponent(tf_distanciaTierra1)
                            .addGroup(ModificarPlanetaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(rd_anillos1)
                                .addGap(0, 44, Short.MAX_VALUE)))))
                .addGap(160, 160, 160))
            .addGroup(ModificarPlanetaLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jb_modificarPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificarPlanetaLayout.setVerticalGroup(
            ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarPlanetaLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel41)
                .addGap(20, 20, 20)
                .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombrePlaneta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_tempMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tipoSuperficie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(ModificarPlanetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_distanciaTierra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(29, 29, 29)
                .addComponent(rd_anillos1)
                .addGap(46, 46, 46)
                .addComponent(jb_modificarPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel44.setText("Numero de serie");

        tf_numeroSerieNave1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_numeroSerieNave1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_lugarDespejeNave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lugarDespejeNave1ActionPerformed(evt);
            }
        });

        jLabel45.setText("Velocidad");

        jLabel46.setText("Lugar de despeje");

        jLabel47.setText("Planeta de destino");

        jLabel48.setText("Astronautas");

        jb_modificarNave.setText("Modificar");
        jb_modificarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarNaveActionPerformed(evt);
            }
        });

        cb_planetaDestinoNave1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_astronautaNave1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel49.setText("MODIFICAR NAVE TRIPULADA");

        agregar2.setText("Agregar");
        agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarNaveLayout = new javax.swing.GroupLayout(ModificarNave.getContentPane());
        ModificarNave.getContentPane().setLayout(ModificarNaveLayout);
        ModificarNaveLayout.setHorizontalGroup(
            ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarNaveLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarNaveLayout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificarNaveLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel47)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_numeroSerieNave1)
                            .addComponent(tf_velocidadNave1)
                            .addComponent(tf_lugarDespejeNave1)
                            .addGroup(ModificarNaveLayout.createSequentialGroup()
                                .addComponent(jb_modificarNave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cb_planetaDestinoNave1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_astronautaNave1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(agregar2)))
                .addGap(44, 44, 44))
        );
        ModificarNaveLayout.setVerticalGroup(
            ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarNaveLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel49)
                .addGap(20, 20, 20)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_numeroSerieNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(tf_velocidadNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_lugarDespejeNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(24, 24, 24)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(cb_planetaDestinoNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ModificarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(cb_astronautaNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar2))
                .addGap(85, 85, 85)
                .addComponent(jb_modificarNave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        cb_planetaDestinoSonda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel50.setText("Material");

        jLabel51.setText("Numero de serie");

        jb_modificarSonda.setText("Modificar");
        jb_modificarSonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarSondaActionPerformed(evt);
            }
        });

        tf_numeroSerieSonda1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_numeroSerieSonda1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel52.setText("MODIFICAR SONDA ESPACIAL");

        tf_materialSonda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialSonda1ActionPerformed(evt);
            }
        });

        jLabel53.setText("Velocidad");

        jLabel54.setText("Planeta de destino");

        jLabel55.setText("Peso");

        javax.swing.GroupLayout ModificarSondaLayout = new javax.swing.GroupLayout(ModificarSonda.getContentPane());
        ModificarSonda.getContentPane().setLayout(ModificarSondaLayout);
        ModificarSondaLayout.setHorizontalGroup(
            ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarSondaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarSondaLayout.createSequentialGroup()
                        .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel54)
                            .addComponent(jLabel51)
                            .addComponent(jLabel53)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_numeroSerieSonda1)
                            .addComponent(tf_velocidadSonda1)
                            .addComponent(tf_materialSonda1)
                            .addComponent(jb_modificarSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_planetaDestinoSonda1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_pesoSonda1))
                        .addGap(63, 63, 63))
                    .addGroup(ModificarSondaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ModificarSondaLayout.setVerticalGroup(
            ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarSondaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel52)
                .addGap(18, 18, 18)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_numeroSerieSonda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(tf_velocidadSonda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_materialSonda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(24, 24, 24)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(cb_planetaDestinoSonda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ModificarSondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(tf_pesoSonda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jb_modificarSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Expedicion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ExpedicionStateChanged(evt);
            }
        });

        jLabel5.setText("Sueldo");

        jLabel7.setText("Experiencia");

        jb_crearAstronauta.setText("Crear");
        jb_crearAstronauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearAstronautaActionPerformed(evt);
            }
        });

        jLabel8.setText("AGREGAR ASTRONAUTAS");

        jLabel9.setText("Nombre");

        tf_nombreAstronauta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_nombreAstronautaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_sueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sueldoActionPerformed(evt);
            }
        });

        jLabel10.setText("Nacionalidad");

        jLabel11.setText("Sexo");

        jLabel12.setText("Peso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_sexo)
                    .addComponent(tf_nombreAstronauta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_experiencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pesoAstronauta)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_crearAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(160, 160, 160))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pesoAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(76, 76, 76)
                .addComponent(jb_crearAstronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Expedicion.addTab("Crear Astronauta", jPanel3);

        jLabel13.setText("Lugar de despeje");

        jb_crearNave.setText("Crear");
        jb_crearNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearNaveActionPerformed(evt);
            }
        });

        jLabel15.setText("AGREGAR NAVE TRIPULADA");

        jLabel16.setText("Numero de serie");

        tf_numeroSerieNave.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_numeroSerieNaveAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_lugarDespejeNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lugarDespejeNaveActionPerformed(evt);
            }
        });

        jLabel17.setText("Velocidad");

        jLabel18.setText("Planeta de destino");

        jLabel19.setText("Astronautas");

        cb_planetaDestinoNave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_astronautaNave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agregar1.setText("Agregar");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_numeroSerieNave, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(tf_velocidadNave)
                    .addComponent(tf_lugarDespejeNave)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jb_crearNave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cb_planetaDestinoNave, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_astronautaNave, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(agregar1)
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_numeroSerieNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_velocidadNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_lugarDespejeNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_planetaDestinoNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_astronautaNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar1))
                .addGap(85, 85, 85)
                .addComponent(jb_crearNave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Expedicion.addTab("Crear Nave Tripulada", jPanel4);

        jLabel20.setText("Numero de serie");

        tf_numeroSerieSonda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_numeroSerieSondaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_materialSonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialSondaActionPerformed(evt);
            }
        });

        jLabel21.setText("Velocidad");

        jLabel22.setText("Planeta de destino");

        jLabel23.setText("Peso");

        cb_planetaDestinoSonda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Material");

        jb_crearSonda.setText("Crear");
        jb_crearSonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearSondaActionPerformed(evt);
            }
        });

        jLabel24.setText("AGREGAR NAVE SONDA ESPACIAL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_numeroSerieSonda, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(tf_velocidadSonda)
                    .addComponent(tf_materialSonda)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jb_crearSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cb_planetaDestinoSonda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_pesoSonda))
                .addGap(158, 158, 158))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel24)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_numeroSerieSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_velocidadSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_materialSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_planetaDestinoSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_pesoSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jb_crearSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Expedicion.addTab("Crear Sonda Espacial", jPanel5);

        tablaSondas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Planeta Destino", "Velocidad", "Material", "Peso"
            }
        ));
        tablaSondas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSondasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSondas);

        tablaNaves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Planeta Destino", "Velocidad", "Lugar de Despeje"
            }
        ));
        tablaNaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaNavesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaNaves);

        tablaAstronautas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacinalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
            }
        ));
        tablaAstronautas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAstronautasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaAstronautas);

        tablaPlanetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "TempMedia", "Anillos", "Superficie", "DistanciaTierra"
            }
        ));
        tablaPlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPlanetasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaPlanetas);

        jLabel25.setText("Planetas");

        jLabel26.setText("Astronautas");

        jLabel27.setText("Sondas espaciales");

        jLabel28.setText("Naves tripuladas");

        jb_guardar.setText("Guardar informacion");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_cargar.setText("Cargar informacion");
        jb_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jb_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_cargar)
                .addGap(108, 108, 108))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel28)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardar)
                    .addComponent(jb_cargar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Expedicion.addTab("Inventario", jPanel6);

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel29.setText("EXPEDICION");

        CB_planeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_nave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Planeta");

        jLabel31.setText("Nave");

        estado.setBackground(new java.awt.Color(51, 255, 0));
        estado.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 0, 0));
        estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado.setText("Viaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 180, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_nave, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel29)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_nave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Expedicion.addTab("Expedicion", jPanel1);

        tf_nombrePlaneta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tf_nombrePlanetaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tf_tipoSuperficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tipoSuperficieActionPerformed(evt);
            }
        });

        jLabel3.setText("Temp. media");

        jLabel4.setText("Tipo de superficie");

        jLabel6.setText("Distancia con la tierra");

        jb_crearPlaneta.setText("Crear");
        jb_crearPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearPlanetaActionPerformed(evt);
            }
        });

        rd_anillos.setText("Posee anillos");

        jLabel1.setText("AGREGAR PLANETAS");

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombrePlaneta, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(tf_tempMedia)
                            .addComponent(tf_tipoSuperficie)
                            .addComponent(tf_distanciaTierra)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_crearPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(rd_anillos)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(160, 160, 160))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombrePlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_tempMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tipoSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_distanciaTierra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(rd_anillos)
                .addGap(89, 89, 89)
                .addComponent(jb_crearPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Expedicion.addTab("Crear Planeta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Expedicion)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Expedicion)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tipoSuperficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tipoSuperficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tipoSuperficieActionPerformed

    private void tf_nombrePlanetaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_nombrePlanetaAncestorAdded

    }//GEN-LAST:event_tf_nombrePlanetaAncestorAdded

    private void tf_nombreAstronautaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_nombreAstronautaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreAstronautaAncestorAdded

    private void tf_sueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sueldoActionPerformed

    private void tf_numeroSerieNaveAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_numeroSerieNaveAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroSerieNaveAncestorAdded

    private void tf_lugarDespejeNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lugarDespejeNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lugarDespejeNaveActionPerformed

    private void tf_numeroSerieSondaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_numeroSerieSondaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroSerieSondaAncestorAdded

    private void tf_materialSondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialSondaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialSondaActionPerformed

    private void jb_crearPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearPlanetaActionPerformed

        boolean ttt;
        if (rd_anillos.isSelected()) {
            ttt = true;
        } else {
            ttt = false;
        }
        Planeta temp = new Planeta(tf_nombrePlaneta.getText(), tf_tipoSuperficie.getText(), ttt,
                Double.parseDouble(tf_distanciaTierra.getText()), Double.parseDouble(tf_tempMedia.getText()));
        listPlanetas.add(temp);
        JOptionPane.showMessageDialog(this, "Agregado");
    }//GEN-LAST:event_jb_crearPlanetaActionPerformed

    private void jb_crearAstronautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearAstronautaActionPerformed

        Astronauta temp = new Astronauta(tf_nombreAstronauta.getText(), tf_nacionalidad.getText(), tf_experiencia.getText(),
                tf_sexo.getText(), Double.parseDouble(tf_sueldo.getText()), Double.parseDouble(tf_pesoAstronauta.getText()));
        listAstronautas.add(temp);
        JOptionPane.showMessageDialog(this, "Agregado");
    }//GEN-LAST:event_jb_crearAstronautaActionPerformed

    private void jb_crearNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearNaveActionPerformed

        NaveTripulada temp = new NaveTripulada(tf_lugarDespejeNave.getText(), tf_numeroSerieNave.getText(),
                ((Planeta) cb_planetaDestinoNave.getSelectedItem()), Double.parseDouble(tf_velocidadNave.getText()));

        listNaves.add(temp);
        JOptionPane.showMessageDialog(this, "Agregado");
        actualNave = temp;
    }//GEN-LAST:event_jb_crearNaveActionPerformed

    private void jb_crearSondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearSondaActionPerformed
        //public SondaEspacial(String material, double peso, String numSerie, Planeta planetaDestino, double velocidad) {

        SondaEspacial temp = new SondaEspacial(tf_materialSonda.getText(), Double.parseDouble(tf_pesoSonda.getText()),
                tf_numeroSerieSonda.getText(), ((Planeta) cb_planetaDestinoSonda.getSelectedItem()), Double.parseDouble(tf_velocidadSonda.getText()));
        listSondas.add(temp);
        JOptionPane.showMessageDialog(this, "Agregado");
    }//GEN-LAST:event_jb_crearSondaActionPerformed

    public void actualizarInventario() {
        DefaultComboBoxModel modeloPlaneta = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloAstronauta = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloNave = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloNaves = new DefaultComboBoxModel();

        DefaultTableModel planetas = (DefaultTableModel) tablaPlanetas.getModel();
        DefaultTableModel astronautas = (DefaultTableModel) tablaAstronautas.getModel();
        DefaultTableModel naves = (DefaultTableModel) tablaNaves.getModel();
        DefaultTableModel sondas = (DefaultTableModel) tablaSondas.getModel();

        while (planetas.getRowCount() > 0) {
            planetas.removeRow(0);
        }
        while (astronautas.getRowCount() > 0) {
            astronautas.removeRow(0);
        }
        while (naves.getRowCount() > 0) {
            naves.removeRow(0);
        }
        while (sondas.getRowCount() > 0) {
            sondas.removeRow(0);
        }

        for (Planeta p : listPlanetas) {
            modeloPlaneta.addElement(p);
            Object[] temp = {p.getNombre(), p.getTempMedia(), p.isAnillos(), p.getTipoSuperficie(), p.getDistanciaTierra()};
            planetas.addRow(temp);

        }
        for (Astronauta a : listAstronautas) {

            Object[] temp = {a.getNombre(), a.getNacionalidad(), a.getSueldo(), a.getExperiencia(), a.getSexo(), a.getPeso()};
            astronautas.addRow(temp);
            if (a.isAgregado()) {

            } else {
                modeloAstronauta.addElement(a);
            }

        }
        for (NaveTripulada n : listNaves) {
            modeloNave.addElement(n);
            modeloNaves.addElement(n);
            Object[] temp = {n.getNumSerie(), n.getPlanetaDestino(), n.getVelocidad(), n.getLugarDespeje()};
            naves.addRow(temp);

        }
        for (SondaEspacial n : listSondas) {
            modeloNave.addElement(n);
            modeloNaves.addElement(n);
            Object[] temp = {n.getNumSerie(), n.getPlanetaDestino(), n.getVelocidad(), n.getMaterial(), n.getPeso()};
            sondas.addRow(temp);
        }

        cb_planetaDestinoNave.setModel(modeloPlaneta);
        cb_planetaDestinoSonda.setModel(modeloPlaneta);
        CB_planeta.setModel(modeloPlaneta);
        cb_astronautaNave.setModel(modeloAstronauta);
        CB_nave.setModel(modeloNaves);

        cb_planetaDestinoNave1.setModel(modeloPlaneta);
        cb_planetaDestinoSonda1.setModel(modeloPlaneta);
        cb_astronautaNave1.setModel(modeloAstronauta);

    }

    private void ExpedicionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ExpedicionStateChanged

        actualizarInventario();

    }//GEN-LAST:event_ExpedicionStateChanged

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed

        actualNave.getListAstronautas().add((Astronauta) cb_astronautaNave.getSelectedItem());
        ((Astronauta) cb_astronautaNave.getSelectedItem()).setAgregado(true);
        actualizarInventario();


    }//GEN-LAST:event_agregar1ActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        adminArchivo puente = new adminArchivo("./informacion.m17");
        puente.setListAstronautas(listAstronautas);
        puente.setListNaves(listNaves);
        puente.setListPlanetas(listPlanetas);
        puente.setListSondas(listSondas);
        try {
            puente.escribirArchivo();
        } catch (IOException ex) {

        }
        JOptionPane.showMessageDialog(this, "Guardado");

    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cargarActionPerformed
        adminArchivo puente = new adminArchivo("./informacion.m17");
        puente.cargarArchivo();
        listAstronautas = puente.getListAstronautas();
        listPlanetas = puente.getListPlanetas();
        listNaves = puente.getListNaves();
        listSondas = puente.getListSondas();
        actualizarInventario();
        JOptionPane.showMessageDialog(this, "Cargado");
    }//GEN-LAST:event_jb_cargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Expedicion exp = new Expedicion(((Planeta) CB_planeta.getSelectedItem()), ((NaveEspacial) CB_nave.getSelectedItem()), estado);

        exp.start();

        if (((NaveEspacial) CB_nave.getSelectedItem()) instanceof NaveTripulada) {

            for (Astronauta a : ((NaveTripulada) CB_nave.getSelectedItem()).getListAstronautas()) {
                a.setAgregado(false);
            }
        }

        if (((NaveEspacial) CB_nave.getSelectedItem()) instanceof NaveTripulada) {

            listNaves.remove(((NaveTripulada) CB_nave.getSelectedItem()));

        } else {
            listSondas.remove(((SondaEspacial) CB_nave.getSelectedItem()));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_modificarAstronautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarAstronautaActionPerformed
        
        actualAstronauta.setNombre(tf_nombreAstronauta1.getText());
        actualAstronauta.setNacionalidad(tf_nacionalidad1.getText());
        actualAstronauta.setExperiencia(tf_experiencia1.getText());
        actualAstronauta.setSexo(tf_sexo1.getText());
        actualAstronauta.setSueldo(Double.parseDouble(tf_sueldo1.getText()));
        actualAstronauta.setPeso(Double.parseDouble(tf_pesoAstronauta1.getText()));
        JOptionPane.showMessageDialog(null,"Modificado");
        
        
        
    }//GEN-LAST:event_jb_modificarAstronautaActionPerformed

    private void tf_nombreAstronauta1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_nombreAstronauta1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreAstronauta1AncestorAdded

    private void tf_sueldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sueldo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sueldo1ActionPerformed

    private void jb_modificarPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarPlanetaActionPerformed
        actualPlaneta.setNombre(tf_nombreAstronauta1.getText());
        actualPlaneta.setTempMedia(Double.parseDouble(tf_tempMedia1.getText()));
        actualPlaneta.setTipoSuperficie(tf_tipoSuperficie1.getText());
        actualPlaneta.setDistanciaTierra(Double.parseDouble(tf_distanciaTierra1.getText()));
               
        JOptionPane.showMessageDialog(null,"Modificado");
    }//GEN-LAST:event_jb_modificarPlanetaActionPerformed

    private void tf_nombrePlaneta1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_nombrePlaneta1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombrePlaneta1AncestorAdded

    private void tf_tipoSuperficie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tipoSuperficie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tipoSuperficie1ActionPerformed

    private void tf_numeroSerieNave1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_numeroSerieNave1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroSerieNave1AncestorAdded

    private void tf_lugarDespejeNave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lugarDespejeNave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lugarDespejeNave1ActionPerformed

    private void jb_modificarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarNaveActionPerformed
        actualNave.setNumSerie(tf_numeroSerieNave1.getText());
        actualNave.setLugarDespeje(tf_lugarDespejeNave1.getText());
        actualNave.setPlanetaDestino((Planeta)cb_planetaDestinoNave1.getSelectedItem());
        actualNave.setVelocidad(Double.parseDouble(tf_velocidadNave1.getText()));
        
               
        JOptionPane.showMessageDialog(null,"Modificado");
    }//GEN-LAST:event_jb_modificarNaveActionPerformed

    private void agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar2ActionPerformed

    private void jb_modificarSondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarSondaActionPerformed
        actualSonda.setNumSerie(tf_numeroSerieSonda1.getText());
        actualSonda.setPlanetaDestino((Planeta)cb_planetaDestinoSonda1.getSelectedItem());
        actualSonda.setVelocidad(Double.parseDouble(tf_velocidadSonda1.getText()));
        actualSonda.setMaterial(tf_materialSonda1.getText());
        actualSonda.setPeso(Double.parseDouble(tf_pesoSonda1.getText()));
               
        JOptionPane.showMessageDialog(null,"Modificado");
    }//GEN-LAST:event_jb_modificarSondaActionPerformed

    private void tf_numeroSerieSonda1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tf_numeroSerieSonda1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_numeroSerieSonda1AncestorAdded

    private void tf_materialSonda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialSonda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialSonda1ActionPerformed

    private void tablaPlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlanetasMouseClicked
        if (evt.isMetaDown()) {
            ModificarEliminar.show(evt.getComponent(), evt.getX(), evt.getY());
            actualTabla = tablaPlanetas;
        }
    }//GEN-LAST:event_tablaPlanetasMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        if (actualTabla == tablaPlanetas) {
            int pos = actualTabla.getSelectedRow();
            actualPlaneta = listPlanetas.get(pos);
            ModificarPlaneta.setVisible(true);
            ModificarPlaneta.pack();

            tf_nombrePlaneta1.setText(actualPlaneta.getNombre());
            tf_tipoSuperficie1.setText(actualPlaneta.getTipoSuperficie());
            tf_distanciaTierra1.setText("" + actualPlaneta.getDistanciaTierra());
            tf_tempMedia1.setText("" + actualPlaneta.getTempMedia());
        } else {
            if (actualTabla == tablaAstronautas) {
                int pos = actualTabla.getSelectedRow();
                System.out.println("POS ASTRO: "+pos);
                actualAstronauta = listAstronautas.get(pos);
                ModificarAstronauta.setVisible(true);
                ModificarAstronauta.pack();

                tf_nombreAstronauta1.setText(actualAstronauta.getNombre());
                tf_nacionalidad1.setText(actualAstronauta.getNacionalidad());
                tf_experiencia1.setText(actualAstronauta.getExperiencia());
                tf_sexo1.setText(actualAstronauta.getSexo());
                tf_sueldo1.setText(actualAstronauta.getSueldo() + "");
                tf_pesoAstronauta1.setText(actualAstronauta.getPeso() + "");
            } else {
                if (actualTabla == tablaNaves) {
                    DefaultTableModel m = (DefaultTableModel) actualTabla.getModel();
                    String serial = ((String) m.getValueAt(actualTabla.getSelectedRow(), 0));
                    for (NaveTripulada n : listNaves) {
                        if (n.getNumSerie().equals(serial)) {
                            actualNave = n;
                            break;
                        }
                    }
                    ModificarNave.setVisible(true);
                    ModificarNave.pack();

                    tf_numeroSerieNave1.setText(actualNave.getNumSerie());
                    cb_planetaDestinoNave1.setSelectedItem(actualNave.getPlanetaDestino());
                    tf_velocidadNave1.setText("" + actualNave.getVelocidad());
                    tf_lugarDespejeNave1.setText(actualNave.getLugarDespeje());

                } else {
                    DefaultTableModel m = (DefaultTableModel) actualTabla.getModel();
                    String serial = ((String) m.getValueAt(actualTabla.getSelectedRow(), 0));
                    for (SondaEspacial n : listSondas) {
                        if (n.getNumSerie().equals(serial)) {
                            actualSonda = n;
                            break;
                        }
                    }
                    ModificarSonda.setVisible(true);
                    ModificarSonda.pack();

                    tf_numeroSerieSonda1.setText(actualSonda.getNumSerie());
                    cb_planetaDestinoSonda1.setSelectedItem(actualSonda.getPlanetaDestino());
                    tf_velocidadSonda1.setText("" + actualSonda.getVelocidad());
                    tf_materialSonda1.setText(actualSonda.getMaterial());
                    tf_pesoSonda1.setText(actualSonda.getPeso() + "");

                }
            }
        }
        actualizarInventario();
    }//GEN-LAST:event_ModificarActionPerformed

    private void tablaAstronautasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAstronautasMouseClicked
        if (evt.isMetaDown()) {
            ModificarEliminar.show(evt.getComponent(), evt.getX(), evt.getY());
            actualTabla = tablaAstronautas;
        }
    }//GEN-LAST:event_tablaAstronautasMouseClicked

    private void tablaNavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaNavesMouseClicked
        if (evt.isMetaDown()) {
            ModificarEliminar.show(evt.getComponent(), evt.getX(), evt.getY());
            actualTabla = tablaNaves;
        }
    }//GEN-LAST:event_tablaNavesMouseClicked

    private void tablaSondasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSondasMouseClicked
        if (evt.isMetaDown()) {
            ModificarEliminar.show(evt.getComponent(), evt.getX(), evt.getY());
            actualTabla = tablaNaves;
        }
    }//GEN-LAST:event_tablaSondasMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        if (actualTabla == tablaPlanetas) {
            int pos = actualTabla.getSelectedRow();
            listPlanetas.remove(pos);
        } else {
            if (actualTabla == tablaAstronautas) {
                int pos = actualTabla.getSelectedRow();
                listAstronautas.remove(pos);
            } else {
                if (actualTabla == tablaNaves) {
                    DefaultTableModel m = (DefaultTableModel) actualTabla.getModel();
                    String serial = ((String) m.getValueAt(actualTabla.getSelectedRow(), 0));
                    for (NaveTripulada n : listNaves) {
                        if (n.getNumSerie().equals(serial)) {
                            listNaves.remove(n);
                            break;
                        }
                    }
                } else {
                    DefaultTableModel m = (DefaultTableModel) actualTabla.getModel();
                    String serial = ((String) m.getValueAt(actualTabla.getSelectedRow(), 0));
                    for (SondaEspacial n : listSondas) {
                        if (n.getNumSerie().equals(serial)) {
                            listSondas.remove(n);
                            break;
                        }
                    }
                }
            }
        }
        actualizarInventario();
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NASA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NASA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NASA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NASA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NASA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_nave;
    private javax.swing.JComboBox<String> CB_planeta;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JTabbedPane Expedicion;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JDialog ModificarAstronauta;
    private javax.swing.JPopupMenu ModificarEliminar;
    private javax.swing.JDialog ModificarNave;
    private javax.swing.JDialog ModificarPlaneta;
    private javax.swing.JDialog ModificarSonda;
    private javax.swing.JButton agregar1;
    private javax.swing.JButton agregar2;
    private javax.swing.JComboBox<String> cb_astronautaNave;
    private javax.swing.JComboBox<String> cb_astronautaNave1;
    private javax.swing.JComboBox<String> cb_planetaDestinoNave;
    private javax.swing.JComboBox<String> cb_planetaDestinoNave1;
    private javax.swing.JComboBox<String> cb_planetaDestinoSonda;
    private javax.swing.JComboBox<String> cb_planetaDestinoSonda1;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_crearAstronauta;
    private javax.swing.JButton jb_crearNave;
    private javax.swing.JButton jb_crearPlaneta;
    private javax.swing.JButton jb_crearSonda;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificarAstronauta;
    private javax.swing.JButton jb_modificarNave;
    private javax.swing.JButton jb_modificarPlaneta;
    private javax.swing.JButton jb_modificarSonda;
    private javax.swing.JRadioButton rd_anillos;
    private javax.swing.JRadioButton rd_anillos1;
    private javax.swing.JTable tablaAstronautas;
    private javax.swing.JTable tablaNaves;
    private javax.swing.JTable tablaPlanetas;
    private javax.swing.JTable tablaSondas;
    private javax.swing.JTextField tf_distanciaTierra;
    private javax.swing.JTextField tf_distanciaTierra1;
    private javax.swing.JTextField tf_experiencia;
    private javax.swing.JTextField tf_experiencia1;
    private javax.swing.JTextField tf_lugarDespejeNave;
    private javax.swing.JTextField tf_lugarDespejeNave1;
    private javax.swing.JTextField tf_materialSonda;
    private javax.swing.JTextField tf_materialSonda1;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nacionalidad1;
    private javax.swing.JTextField tf_nombreAstronauta;
    private javax.swing.JTextField tf_nombreAstronauta1;
    private javax.swing.JTextField tf_nombrePlaneta;
    private javax.swing.JTextField tf_nombrePlaneta1;
    private javax.swing.JTextField tf_numeroSerieNave;
    private javax.swing.JTextField tf_numeroSerieNave1;
    private javax.swing.JTextField tf_numeroSerieSonda;
    private javax.swing.JTextField tf_numeroSerieSonda1;
    private javax.swing.JTextField tf_pesoAstronauta;
    private javax.swing.JTextField tf_pesoAstronauta1;
    private javax.swing.JTextField tf_pesoSonda;
    private javax.swing.JTextField tf_pesoSonda1;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_sueldo1;
    private javax.swing.JTextField tf_tempMedia;
    private javax.swing.JTextField tf_tempMedia1;
    private javax.swing.JTextField tf_tipoSuperficie;
    private javax.swing.JTextField tf_tipoSuperficie1;
    private javax.swing.JTextField tf_velocidadNave;
    private javax.swing.JTextField tf_velocidadNave1;
    private javax.swing.JTextField tf_velocidadSonda;
    private javax.swing.JTextField tf_velocidadSonda1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Planeta> listPlanetas = new ArrayList();
    ArrayList<Astronauta> listAstronautas = new ArrayList();
    ArrayList<NaveTripulada> listNaves = new ArrayList();
    ArrayList<SondaEspacial> listSondas = new ArrayList();
    NaveTripulada actualNave;
    SondaEspacial actualSonda;
    Planeta actualPlaneta;
    Astronauta actualAstronauta;
    JTable actualTabla;
}
